/* automatically generated by rust-bindgen 0.59.2 */

#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]

pub type __uint8_t = ::std::os::raw::c_uchar;
pub type size_t = ::std::os::raw::c_ulong;
extern "C" {
    pub fn do_the_thing(inout: *mut u8, inout_size: size_t) -> bool;
}
