/* Copyright (C) 2020 Micah Snyder. */

#ifndef __COLORLOG_H
#define __COLORLOG_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>


void clog_debug(const uint8_t *message, uintptr_t message_len);

void clog_error(const uint8_t *message, uintptr_t message_len);

void clog_info(const uint8_t *message, uintptr_t message_len);

void clog_warning(const uint8_t *message, uintptr_t message_len);

#endif /* __COLORLOG_H */
