[package]
authors = ["Micah Snyder"]
edition = "2021"
name = "gen_uuid"
version = "0.2.0"

[dependencies]
libc = "0.2.77"

[dependencies.uuid]
version = "0.8.1"
features = ["v4"]

[lib]
crate-type = ["staticlib", "lib"]
name = "gen_uuid"

[build-dependencies]
cbindgen = "0.20"
