name: Build Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    name: "${{ matrix.os }}: build and test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable-x86_64-unknown-linux-gnu

      - name: get-cmake
        uses: lukka/get-cmake@latest

      - name: Build project
        working-directory: "${{ runner.workspace }}/"
        run: |
          cmake -B ./build -S ./cmake-rust-demo
          cmake --build ./build

      - name: Run tests
        working-directory: "${{ runner.workspace }}/build/"
        run: |
          ctest -VV

      - name: Run the app
        run: |
          ${{ runner.workspace }}/build/app/app

  build_and_test_windows:
    name: "windows-latest: build and test"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable-x86_64-unknown-linux-gnu

      - name: get-cmake
        uses: lukka/get-cmake@latest

      - name: Build project
        working-directory: "${{ runner.workspace }}/"
        run: |
          cmake -B ./build -S ./cmake-rust-demo -A x64
          cmake --build ./build

      - name: Run tests
        working-directory: "${{ runner.workspace }}/build/"
        run: |
          ctest -VV -C Debug

      - name: Run the app
        run: |
          ${{ runner.workspace }}\\build\\app\\Debug\\app.exe
